apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
    retries:
      attempts: 10
      perTryTimeout: 1s
      retryOn: "unavailable,5xx,retriable-4xx"