apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: frontend
spec:
  defaultSubset: 'v1'
  subsets:
    'v1':
      filter: 'Service.Meta.version == v1'
    'v2':
      filter: 'Service.Meta.version == v2'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: frontend
spec:
  routes:
    - destination:
        service: frontend
        numRetries: 20
        retryOnStatusCodes: [500, 501, 502, 503]
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: frontend
spec:
  splits:
    - weight: 50
      serviceSubset: v1
    - weight: 50
      serviceSubset: v2